name: Terraform Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  deploy:
    name: Deploy Terraform Infrastructure
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      KEY_NAME: ${{ secrets.AWS_KEY_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tf.plan -var="key_name=${KEY_NAME}"

    - name: Terraform Apply
      run: terraform apply -auto-approve tf.plan
